services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: dio_springboot
      MYSQL_ROOT_PASSWORD: italo123
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: gerenciador-cursos-api
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dio_springboot?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=italo123